### Create a Comment
POST http://localhost:3000/comments
Content-Type: application/json
{
    "content": "This is a sample comment",
    "user": "SampleUser",
    "postId": "VALID_POST_ID"
}

### Get All Comments
GET http://localhost:3000/comments
Content-Type: application/json

### Get Comments for a Specific Post by ID
GET http://localhost:3000/comments/VALID_POST_ID
Content-Type: application/json

### Get Comments for a Specific User by Username
GET http://localhost:3000/comments/user/SampleUser

### POST request to create a new post
POST http://localhost:3000/post
Content-Type: application/json
{
  "sender": "1234",
  "message": "This is a new post!",
  "timestamp": "2024-11-27T12:00:00Z"
}

### GET request to fetch all posts 
GET http://localhost:3000/post
Content-Type: application/json

### GET request to fetch posts by a specific sender
GET http://localhost:3000/post?sender=1234
Content-Type: application/json

### Get a Comment for a Specific Comment ID
GET http://localhost:3000/comments/getComment/VALID_COMMENT_ID

### GET request to fetch a specific post by ID
GET http://localhost:3000/post/60d9f9f9f9f9f9f9f9f9f9f9
Content-Type: application/json

### Update a Comment
PUT http://localhost:3000/comments/VALID_COMMENT_ID
Content-Type: application/json
{
    "content": "Updated comment content"
}

### Delete a Comment by ID
DELETE http://localhost:3000/comments/VALID_COMMENT_ID
Content-Type: application/json

### Delete All Comments
DELETE http://localhost:3000/comments
Content-Type: application/json


### PUT request to update a specific post by ID
PUT http://localhost:3000/post/60d9f9f9f9f9f9f9f9f9f9f9
Content-Type: application/json
{
  "message": "Updated message content!"
}
